# -*- coding: utf-8 -*-
"""io.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15H7TpzLIZuekyo-m3W-ZMa-NwjS-e9OO
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kurtosis, skew
from google.colab import drive
from sklearn.linear_model import LogisticRegression
from sklearn.utils import resample

# Constantes
DRIVE_MOUNT_PATH = "/content/drive"
GRAPHPATH = os.path.join(DRIVE_MOUNT_PATH, "MyDrive/graficos")
SUMMARYPATH = os.path.join(DRIVE_MOUNT_PATH, "MyDrive/sumarios")
PALETTE = sns.color_palette("viridis", as_cmap=True)
FIGSIZE = (10, 6)
CSV_FILEPATH = "https://docs.google.com/spreadsheets/d/1ph_tzoDnLRvzXJNon5fAULSUtBH_u11aNLg2uw0Riqc/export?format=csv&gid=1229730846"
N_BOOTSTRAP = 2000
TOP_COUNTRIES = 15

# Criação de diretórios
os.makedirs(GRAPHPATH, exist_ok=True)
os.makedirs(SUMMARYPATH, exist_ok=True)

# Montar o Google Drive
drive.mount(DRIVE_MOUNT_PATH, force_remount=True)

# Função para converter números no formato errado (com pontos ao invés de vírgulas)
def convert_to_float(val):
    try:
        # Substitui os pontos por nada e tenta converter para float
        return float(val.replace('.', '').replace(',', '.'))
    except:
        return np.nan

# Carregar os dados
try:
    df = pd.read_csv(CSV_FILEPATH, on_bad_lines='skip')

    # Limpar as colunas de Life Expectancy e Life Satisfaction
    df['Life Expectancy'] = df['Estimates; 1950 - 2020: Annually interpolated demographic indicators - Life expectancy at birth; both sexes combined (years)'].apply(convert_to_float)
    df['Life Satisfaction'] = df['Life satisfaction in Cantril Ladder (World Happiness Report 2022)'].apply(convert_to_float)

    # Converte a coluna de ano para float
    df['Year'] = pd.to_numeric(df['Year'], errors='coerce')

    # Remove linhas com valores faltantes ou inválidos
    df = df.dropna(subset=['Year', 'Life Expectancy', 'Life Satisfaction'])
except Exception as e:
    print(f"Erro ao carregar os dados: {e}")
    exit()

# Bootstrap resampling
def bootstrap(df):
    return resample(df, replace=True, n_samples=len(df))

bootstrapped_df = bootstrap(df)

# Resumo estatístico
def summarize(df, filepath):
    numeric_cols = df.select_dtypes(include=np.number).columns
    summary = df[numeric_cols].describe().T
    summary['variance'] = df[numeric_cols].var()
    summary['skewness'] = df[numeric_cols].apply(skew, axis=0)
    summary['kurtosis'] = df[numeric_cols].apply(kurtosis, axis=0)
    summary.to_csv(filepath)

# Funções de plotagem com fundo preto e paleta viridis
def kde_plot(df, column, title, filename):
    plt.figure(figsize=FIGSIZE)
    sns.set_theme(style="dark", rc={"axes.facecolor": "black", "axes.grid": False})
    sns.kdeplot(df[column], fill=True, color=PALETTE(0.6))
    plt.title(title, color='white')
    plt.xlabel(column, color='white')
    plt.ylabel("Density", color='white')
    plt.xticks(color='white')
    plt.yticks(color='white')
    plt.savefig(os.path.join(GRAPHPATH, filename), dpi=300, bbox_inches='tight', facecolor='black')
    plt.close()

def violin_plot(df, x_column, y_column, title, filename):
    plt.figure(figsize=FIGSIZE)
    sns.set_theme(style="dark", rc={"axes.facecolor": "black", "axes.grid": False})
    sns.violinplot(data=df, x=x_column, y=y_column, palette="viridis")
    plt.title(title, color='white')
    plt.xlabel(x_column, color='white')
    plt.ylabel(y_column, color='white')
    plt.xticks(rotation=45, ha='right', color='white')  # Rotaciona os nomes dos países no eixo x
    plt.yticks(color='white')
    plt.savefig(os.path.join(GRAPHPATH, filename), dpi=300, bbox_inches='tight', facecolor='black')
    plt.close()

def histogram(df, column, title, filename, bins=30):
    plt.figure(figsize=FIGSIZE)
    sns.set_theme(style="dark", rc={"axes.facecolor": "black", "axes.grid": False})
    plt.hist(df[column], bins=bins, color=PALETTE(0.6), edgecolor='white', alpha=0.7)
    plt.title(title, color='white')
    plt.xlabel(column, color='white')
    plt.ylabel('Count', color='white')
    plt.xticks(color='white')
    plt.yticks(color='white')
    plt.savefig(os.path.join(GRAPHPATH, filename), dpi=300, bbox_inches='tight', facecolor='black')
    plt.close()

def logistic_regression_plot(df, x_column, y_column, title, filename):
    plt.figure(figsize=FIGSIZE)
    sns.set_theme(style="dark", rc={"axes.facecolor": "black", "axes.grid": False})
    x = df[x_column].values.reshape(-1, 1)
    y = (df[y_column] > df[y_column].mean()).astype(int)
    model = LogisticRegression().fit(x, y)
    y_pred = model.predict_proba(x)[:, 1]
    plt.scatter(x, y, color=PALETTE(0.4), edgecolor='white', label="Dados")
    plt.plot(x, y_pred, color=PALETTE(0.8), label='Regressão Logística')
    plt.title(title, color='white')
    plt.xlabel(x_column, color='white')
    plt.ylabel(y_column, color='white')
    plt.xticks(color='white')
    plt.yticks(color='white')
    plt.legend()
    plt.savefig(os.path.join(GRAPHPATH, filename), dpi=300, bbox_inches='tight', facecolor='black')
    plt.close()

# Análise para os principais países
top_countries = bootstrapped_df.groupby('Entity')['Life Expectancy'].mean().nlargest(TOP_COUNTRIES).index
top_df = bootstrapped_df[bootstrapped_df['Entity'].isin(top_countries)]

kde_plot(top_df, 'Life Expectancy', 'KDE - Expectativa de Vida (Top 15)', 'kde_life_expectancy_top15.png')
kde_plot(top_df, 'Life Satisfaction', 'KDE - Satisfação de Vida (Top 15)', 'kde_life_satisfaction_top15.png')

violin_plot(top_df, 'Entity', 'Life Expectancy', 'Expectativa de Vida - Gráfico Violino (Top 15)', 'violin_life_expectancy_top15.png')
violin_plot(top_df, 'Entity', 'Life Satisfaction', 'Satisfação de Vida - Gráfico Violino (Top 15)', 'violin_life_satisfaction_top15.png')

histogram(top_df, 'Life Expectancy', 'Histograma - Expectativa de Vida (Top 15)', 'hist_life_expectancy_top15.png')
histogram(top_df, 'Life Satisfaction', 'Histograma - Satisfação de Vida (Top 15)', 'hist_life_satisfaction_top15.png')

logistic_regression_plot(top_df, 'Life Expectancy', 'Life Satisfaction', 'Regressão Logística - Expectativa vs. Satisfação de Vida (Top 15)', 'logistic_regression_top15.png')

summarize(top_df[['Life Expectancy', 'Life Satisfaction']], os.path.join(SUMMARYPATH, "summary_stats.csv"))

print("Gráficos e resumos gerados com sucesso.")