# -*- coding: utf-8 -*-
"""io.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15H7TpzLIZuekyo-m3W-ZMa-NwjS-e9OO
"""

# -*- coding: utf-8 -*-
"""google_colab_notebook_reformulated.ipynb

Reformulado para corrigir o erro de conversão e exibir os gráficos corretamente.
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kurtosis, skew
from google.colab import drive
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.utils import resample

# Constantes com os IDs de pastas e URLs relevantes
DRIVE_MOUNT_PATH = "/content/drive"
GRAFICOS_PATH = os.path.join(DRIVE_MOUNT_PATH, "MyDrive", "graficos")
SUMARIOS_PATH = os.path.join(DRIVE_MOUNT_PATH, "MyDrive", "sumarios")
PALETTE = sns.color_palette("viridis", as_cmap=True)
FIGSIZE = (10, 6)
CSV_FILEPATH = "https://docs.google.com/spreadsheets/d/1ph_tzoDnLRvzXJNon5fAULSUtBH_u11aNLg2uw0Riqc/export?format=csv&gid=1229730846"
N_BOOTSTRAP = 2000
TOP_COUNTRIES = 15

# Verificar se o Google Drive já está montado
if not os.path.ismount(DRIVE_MOUNT_PATH):
    drive.mount(DRIVE_MOUNT_PATH)

# Função para converter strings numéricas com formato incorreto para float
def convert_to_float(val):
    """Converte uma string numérica, possivelmente com separador de milhar, para float."""
    try:
        return float(val.replace('.', '').replace(',', '.'))
    except (ValueError, AttributeError):
        return np.nan

# Carregar os dados do CSV e tratar erros de leitura
try:
    df = pd.read_csv(CSV_FILEPATH, on_bad_lines='skip')

    # Limpeza e conversão de colunas relevantes
    df['Life Expectancy'] = df['Estimates; 1950 - 2020: Annually interpolated demographic indicators - Life expectancy at birth; both sexes combined (years)'].apply(convert_to_float)
    df['Life Satisfaction'] = df['Life satisfaction in Cantril Ladder (World Happiness Report 2022)'].apply(convert_to_float)
    df['Year'] = pd.to_numeric(df['Year'], errors='coerce')

    # Remover linhas com valores faltantes nas colunas de interesse
    df = df.dropna(subset=['Year', 'Life Expectancy', 'Life Satisfaction'])
except Exception as e:
    print(f"Erro ao carregar ou processar os dados: {e}")
    exit()

# Criar DataFrame de bootstrap amostral
bootstrapped_df = resample(df, replace=True, n_samples=len(df), random_state=42)

# Função para gerar um sumário estatístico
def summarize(df, filepath):
    """Calcula e salva um sumário estatístico de colunas numéricas para um arquivo CSV."""
    numeric_cols = df.select_dtypes(include=np.number).columns
    summary = df[numeric_cols].describe().T
    summary['variance'] = df[numeric_cols].var()
    summary['skewness'] = df[numeric_cols].apply(skew, axis=0)
    summary['kurtosis'] = df[numeric_cols].apply(kurtosis, axis=0)
    summary.to_csv(filepath, decimal=",", sep=";")

# Funções para gerar gráficos em diferentes formatos

def kde_plot(df, column, title, filename):
    """Gera e salva um gráfico de KDE (Kernel Density Estimate)."""
    plt.figure(figsize=FIGSIZE)
    sns.set_theme(style="dark", rc={"axes.facecolor": "black", "axes.grid": False})
    sns.kdeplot(df[column], fill=True, color=PALETTE(0.6))
    plt.title(title, color='white')
    plt.xlabel(column, color='white')
    plt.ylabel("Density", color='white')
    plt.xticks(rotation=45, ha='right', color='white')  # Ajustar rotação dos ticks
    plt.yticks(color='white')
    plt.savefig(os.path.join(GRAFICOS_PATH, filename), dpi=300, bbox_inches='tight', facecolor='black')
    plt.close()

def violin_plot(df, x_column, y_column, title, filename):
    """Gera e salva um gráfico de violino bipartido."""
    plt.figure(figsize=FIGSIZE)
    sns.set_theme(style="dark", rc={"axes.facecolor": "black", "axes.grid": False})
    sns.violinplot(data=df, x=x_column, y=y_column, palette="viridis", split=True)
    plt.title(title, color='white')
    plt.xlabel(x_column, color='white')
    plt.ylabel(y_column, color='white')
    plt.xticks(rotation=45, ha='right', color='white')  # Ajustar rotação dos ticks
    plt.yticks(color='white')
    plt.savefig(os.path.join(GRAFICOS_PATH, filename), dpi=300, bbox_inches='tight', facecolor='black')
    plt.close()

def histogram(df, column, title, filename, bins=30):
    """Gera e salva um gráfico de histograma."""
    plt.figure(figsize=FIGSIZE)
    sns.set_theme(style="dark", rc={"axes.facecolor": "black", "axes.grid": False})
    plt.hist(df[column], bins=bins, color=PALETTE(0.6), edgecolor='white', alpha=0.7)
    plt.title(title, color='white')
    plt.xlabel(column, color='white')
    plt.ylabel('Count', color='white')
    plt.xticks(rotation=45, ha='right', color='white')  # Ajustar rotação dos ticks
    plt.yticks(color='white')
    plt.savefig(os.path.join(GRAFICOS_PATH, filename), dpi=300, bbox_inches='tight', facecolor='black')
    plt.close()

def polynomial_regression_plot(df, x_column, y_column, degree, title, filename):
    """Gera e salva um gráfico de regressão polinomial."""
    plt.figure(figsize=FIGSIZE)
    sns.set_theme(style="dark", rc={"axes.facecolor": "black", "axes.grid": False})

    # Preparar os dados para regressão polinomial
    x = df[x_column].values.reshape(-1, 1)
    y = df[y_column].values

    poly = PolynomialFeatures(degree=degree)
    x_poly = poly.fit_transform(x)

    model = LinearRegression().fit(x_poly, y)
    y_pred = model.predict(x_poly)

    plt.scatter(x, y, color=PALETTE(0.4), edgecolor='white', label="Data", alpha=0.7)
    plt.plot(x, y_pred, color=PALETTE(0.8), label=f'Polynomial Regression (Degree {degree})')
    plt.title(title, color='white')
    plt.xlabel(x_column, color='white')
    plt.ylabel(y_column, color='white')
    plt.xticks(rotation=45, ha='right', color='white')  # Ajustar rotação dos ticks
    plt.yticks(color='white')
    plt.legend()
    plt.savefig(os.path.join(GRAFICOS_PATH, filename), dpi=300, bbox_inches='tight', facecolor='black')
    plt.close()

# Análise para os principais países
top_countries = bootstrapped_df.groupby('Entity')['Life Expectancy'].mean().nlargest(TOP_COUNTRIES).index
top_df = bootstrapped_df[bootstrapped_df['Entity'].isin(top_countries)]

# Gerar gráficos para os principais países
kde_plot(top_df, 'Life Expectancy', 'KDE - Life Expectancy (Top 15)', 'kde_life_expectancy_top15.png')
kde_plot(top_df, 'Life Satisfaction', 'KDE - Life Satisfaction (Top 15)', 'kde_life_satisfaction_top15.png')

# Gráficos de violino bipartido
violin_plot(top_df, 'Entity', 'Life Expectancy', 'Violin Plot - Life Expectancy by Country (Top 15)', 'violin_life_expectancy_top15.png')
violin_plot(top_df, 'Entity', 'Life Satisfaction', 'Violin Plot - Life Satisfaction by Country (Top 15)', 'violin_life_satisfaction_top15.png')

# Regressão polinomial
polynomial_regression_plot(top_df, 'Life Expectancy', 'Life Satisfaction', degree=3, title='Polynomial Regression (Degree 3) - Life Expectancy vs. Life Satisfaction', filename='polynomial_regression_life_expectancy_vs_life_satisfaction.png')

# Gerar sumário estatístico
summarize(top_df[['Life Expectancy', 'Life Satisfaction']], os.path.join(SUMARIOS_PATH, "summary_stats.csv"))

print("Gráficos e sumários gerados com sucesso.")